# Generated by Django 4.2.23 on 2025-10-29 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('nivel_acesso', models.IntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2'), (3, 'Nível 3')], default=1)),
                ('divisao', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, help_text='Deixe em branco para gerar automaticamente.', unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColetaDeFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('encoding', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_data', to='registro.funcionario')),
            ],
        ),
    ]
